### ISSUE TITLE
Data from database not displayed on admin.html.

### ISSUE THREAD

**Issue by Shehbaaz-Raees** [Shehbaaz-Raees/E-Voting-App#3]
Hello everyone,

I am currently working on my Spring Boot project and I am having some issues with the AdminController and admin.html. Specifically, I have a method in the controller that retrieves a list of candidates from the database and returns it to the admin.html view. However, when I try to display the candidate data in the admin.html view using a th:loop, it is not working as expected.

Here's what I've tried so far:

- I have checked the database and confirmed that the candidate data is being stored correctly.
- I have verified that the AdminController method is correctly retrieving the candidate data from the database.
- I have added some debug statements to the admin.html view to see if the th:loop is iterating over the candidate data, but it doesn't seem to be working correctly.
At this point, I'm a bit stuck and I'm hoping that someone could help me out with this issue. Any suggestions or tips would be greatly appreciated.

Thanks in advance for your help!

**Comment by kupras06** [comment]
@Shehbaaz-Raees Is it fine if I provide a fix for this issue?

**Comment by Shehbaaz-Raees** [comment]
Hi,

Thanks for reaching out.

Please contribute if you can. I am unable to do figure out what's the
problem.
Or if you can tell me where is the problem in the code.

**Comment by kupras06** [comment]
Please Review https://github.com/Shehbaaz-Raees/E-Voting-App/pull/5

**Comment by Shehbaaz-Raees** [comment]
Hi Prashant,

Thank you for your recent contribution to my Spring Boot project on GitHub.
Your work has helped improve the project and I really appreciate the time
and effort you put into it.
Your contribution is invaluable and I hope we can continue working together
on more projects even better. Once again, thank you for your work.

*=============================================*

*Warm Regards,*
*Khaja Raeesuddin,*
*9021201511.*
